In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import datetime as dt
from datetime import date
import calendar
from calendar import weekday, day_name
import re

In [2]:
key = pd.read_csv('key.csv')
weather = pd.read_csv('weather.csv', parse_dates=['date'])
train = pd.read_csv('train.csv', parse_dates=['date'])

In [3]:
train = pd.merge(train,key)

In [4]:
rt = train[train['units'] > 0].sort_values(by=['units'], ascending=False).reset_index(drop=True)

In [5]:
ls = np.array(['+FC', 'FC', 'TS', 'GR', 'RA', 'DZ', 'SN', 'SG', 'GS', 'PL', 'IC', 'FG+', 
               'FG', 'BR', 'UP', 'HZ', 'FU', 'VA', 'DU', 'DS', 'PO', 'SO', 'SA', 'SS',
                'PY', 'SQ', 'DR', 'SH', 'FZ', 'MI', 'PR', 'BC', 'BL', 'VC'])
list(ls)

['+FC',
 'FC',
 'TS',
 'GR',
 'RA',
 'DZ',
 'SN',
 'SG',
 'GS',
 'PL',
 'IC',
 'FG+',
 'FG',
 'BR',
 'UP',
 'HZ',
 'FU',
 'VA',
 'DU',
 'DS',
 'PO',
 'SO',
 'SA',
 'SS',
 'PY',
 'SQ',
 'DR',
 'SH',
 'FZ',
 'MI',
 'PR',
 'BC',
 'BL',
 'VC']

In [6]:
def validation(token):
    
    result3 = []
    
    for each in ls:
        if each in token:
            token = token.replace(each,'')
            result3.append(each)
    
    return result3

In [67]:
def extract_cs():

    test = list(weather.codesum.unique())

    result = []

    for each in test:
        result.append(validation(each))
    
    return result

In [64]:
cs_iter = (set(validation(token)) for x in weather.codesum)
cs = sorted(set.union(*cs_iter))

dummies = pd.DataFrame(np.zeros((len(weather), len(cs))), columns = cs)


for i, gen in enumerate(weather.codesum):
    dummies.ix[i, validation(gen)] = '1'
    
weather_cs = weather.join(dummies)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:8: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [65]:
weather_cs.DZ.value_counts()

0.0    20020
1        497
Name: DZ, dtype: int64

In [66]:
weather_cs

,station_nbr,date,tmax,tmin,tavg,depart,dewpoint,wetbulb,heat,cool,...,SG,SH,SN,SO,SQ,SS,TS,UP,VA,VC
0,1,2012-01-01,52,31,42,M,36,40,23,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
1,2,2012-01-01,48,33,41,16,37,39,24,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
2,3,2012-01-01,55,34,45,9,24,36,20,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
3,4,2012-01-01,63,47,55,4,28,43,10,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
4,6,2012-01-01,63,34,49,0,31,43,16,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
5,7,2012-01-01,50,33,42,M,26,35,23,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
6,8,2012-01-01,66,45,M,M,34,46,M,M,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
7,9,2012-01-01,34,19,27,M,17,23,38,0,...,0,0.0,0,0.0,0,0.0,0,1,0.0,0
8,10,2012-01-01,73,53,63,M,55,58,2,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
9,11,2012-01-01,72,48,60,7,54,56,5,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
10,12,2012-01-01,72,48,60,M,54,57,5,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
11,13,2012-01-01,38,18,28,M,12,21,37,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
12,14,2012-01-01,50,34,42,5,25,35,23,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
13,15,2012-01-01,48,26,37,16,35,38,28,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
14,16,2012-01-01,50,30,40,M,37,40,25,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
15,17,2012-01-01,56,38,47,M,23,37,18,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
16,18,2012-01-01,59,40,50,4,28,40,15,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
17,19,2012-01-01,38,25,32,10,26,30,33,0,...,0,0.0,1,0.0,0,0.0,0,0,0.0,0
18,20,2012-01-01,59,41,50,M,28,40,15,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
19,1,2012-01-02,50,31,41,M,26,35,24,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20,2,2012-01-02,46,28,37,12,24,32,28,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
21,3,2012-01-02,45,24,35,-1,11,28,30,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
22,4,2012-01-02,60,37,49,-2,26,39,16,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
23,6,2012-01-02,60,30,45,-4,27,38,20,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
24,7,2012-01-02,44,26,35,M,17,29,30,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
25,8,2012-01-02,59,36,M,M,29,40,M,M,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
26,9,2012-01-02,21,11,16,M,8,15,49,0,...,0,0.0,1,0.0,0,0.0,0,1,0.0,0
27,10,2012-01-02,65,45,55,M,33,46,10,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
28,11,2012-01-02,63,40,52,-1,31,44,13,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
29,12,2012-01-02,65,47,56,M,33,46,9,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20487,11,2014-10-30,81,59,70,4,63,65,0,5,...,0,0.0,0,0.0,0,0.0,1,0,0.0,0
20488,12,2014-10-30,81,61,71,M,63,66,0,6,...,0,0.0,0,0.0,0,0.0,1,0,0.0,0
20489,13,2014-10-30,61,32,47,M,26,38,18,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20490,14,2014-10-30,77,45,61,5,39,50,4,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20491,15,2014-10-30,56,30,43,0,36,39,22,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20492,16,2014-10-30,57,34,46,M,39,43,19,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20493,17,2014-10-30,77,43,60,M,41,50,5,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20494,18,2014-10-30,79,56,68,5,51,58,0,3,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20495,19,2014-10-30,51,32,42,-4,33,40,23,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20496,20,2014-10-30,80,52,66,M,50,57,0,1,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20497,1,2014-10-31,53,40,47,M,36,41,18,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20498,2,2014-10-31,49,40,45,0,35,40,20,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20499,3,2014-10-31,55,33,44,-12,32,41,21,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20500,4,2014-10-31,76,56,66,-1,47,56,0,1,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20501,5,2014-10-31,M,M,M,M,37,M,M,M,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20502,6,2014-10-31,76,51,64,0,47,55,1,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20503,7,2014-10-31,58,38,48,M,32,41,17,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20504,8,2014-10-31,78,55,67,M,M,M,0,2,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20505,9,2014-10-31,39,25,32,M,18,27,33,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20506,10,2014-10-31,77,63,70,M,51,59,0,5,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20507,11,2014-10-31,75,50,63,-2,53,57,2,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20508,12,2014-10-31,75,60,68,M,53,59,0,3,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20509,13,2014-10-31,58,35,47,M,28,37,18,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20510,14,2014-10-31,60,38,49,-7,31,42,16,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20511,15,2014-10-31,50,32,41,-2,34,38,24,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20512,16,2014-10-31,53,34,44,M,35,41,21,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20513,17,2014-10-31,59,34,47,M,32,41,18,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20514,18,2014-10-31,67,49,58,-4,40,50,7,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0
20515,19,2014-10-31,45,33,39,-6,24,32,26,0,...,0,0.0,1,0.0,0,0.0,0,0,0.0,0
20516,20,2014-10-31,68,50,59,M,39,50,6,0,...,0,0.0,0,0.0,0,0.0,0,0,0.0,0

In [68]:
df = pd.merge(rt, weather_cs, on=['date', 'station_nbr'])

In [69]:
hol = pd.read_table('holiday_names.txt', sep='\s+', names = ['year', 'month', 'day', 'name'])
hol.tail()

    year month  day             name
53  2014   Jun   15       FathersDay
54  2014   Jul    4  IndependenceDay
55  2014   Sep    1         LaborDay
56  2014   Oct   13      ColumbusDay
57  2014   Oct   31        Halloween

In [70]:
hol.month.unique()

array(['Jan', 'Feb', 'Apr', 'May', 'Jun', 'Jul', 'Sep', 'Oct', 'Nov',
       'Dec', 'Mar'], dtype=object)

In [71]:
dic = {'Jan': 1,
       'Feb': 2,
        'Apr': 4,
        'May': 5,
        'Jun': 6,
        'Jul': 7,
        'Sep': 9,
        'Oct': 10,
        'Nov': 11,
        'Dec': 12,
        'Mar': 5}

hol['monthnumber'] = hol.month.map(dic)

hol.columns = ['year', 'months', 'day', 'name', 'month']


hol = hol.assign(date = pd.to_datetime(hol[['year', 'month', 'day']]))
hol.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
year      58 non-null int64
months    58 non-null object
day       58 non-null int64
name      58 non-null object
month     58 non-null int64
date      58 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 2.8+ KB

In [72]:
hol.tail()

    year months  day             name  month       date
53  2014    Jun   15       FathersDay      6 2014-06-15
54  2014    Jul    4  IndependenceDay      7 2014-07-04
55  2014    Sep    1         LaborDay      9 2014-09-01
56  2014    Oct   13      ColumbusDay     10 2014-10-13
57  2014    Oct   31        Halloween     10 2014-10-31

In [91]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.monthdf['day'] = df['date'].dt.day
df['weekday'] = df[['date']].apply(lambda x: dt.datetime.strftime(x['date'], '%a'), axis=1)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118696 entries, 0 to 118695
Data columns (total 54 columns):
date           118696 non-null datetime64[ns]
store_nbr      118696 non-null int64
item_nbr       118696 non-null int64
units          118696 non-null int64
station_nbr    118696 non-null int64
tmax           118696 non-null object
tmin           118696 non-null object
tavg           118696 non-null object
depart         118696 non-null object
dewpoint       118696 non-null object
wetbulb        118696 non-null object
heat           118696 non-null object
cool           118696 non-null object
sunrise        118696 non-null object
sunset         118696 non-null object
snowfall       118696 non-null object
preciptotal    118696 non-null object
stnpressure    118696 non-null object
sealevel       118696 non-null object
resultspeed    118696 non-null object
resultdir      118696 non-null object
avgspeed       118696 non-null object
BCFG           118696 non-null float64
BLDU           118696 non-null float64
BLSN           118696 non-null float64
BR             118696 non-null float64
DU             118696 non-null float64
DZ             118696 non-null float64
FG             118696 non-null float64
FG+            118696 non-null float64
FU             118696 non-null float64
FZDZ           118696 non-null float64
FZFG           118696 non-null float64
FZRA           118696 non-null float64
GR             118696 non-null float64
GS             118696 non-null float64
HZ             118696 non-null float64
MIFG           118696 non-null float64
PL             118696 non-null float64
PRFG           118696 non-null float64
RA             118696 non-null float64
SG             118696 non-null float64
SN             118696 non-null float64
SQ             118696 non-null float64
TS             118696 non-null float64
TSRA           118696 non-null float64
TSSN           118696 non-null float64
UP             118696 non-null float64
VCFG           118696 non-null float64
VCTS           118696 non-null float64
year           118696 non-null int64
month          118696 non-null int64
day            118696 non-null int64
weekday        118696 non-null object
dtypes: datetime64[ns](1), float64(28), int64(7), object(18)
memory usage: 49.8+ MB

In [13]:
# counting M

columns = list(df.columns)

def count_M(columns):
    ls_M_counting = []
    ls_M_columns= []
    ls_all_counting = []
    
    for i in columns:
        a = df[i].value_counts()
        b = df[i].name
        
        if 'M' in a:
            ls_M_counting.append(a['M'])
            ls_M_columns.append(b)
            ls_all_counting.append(a.sum())
    return ls_M_counting, ls_M_columns, ls_all_counting

        
    
k = count_M(columns)
k = np.array(k).T

M_columns = ['M', 'column', 'total']
dfdf = pd.DataFrame(data = k, columns = M_columns)
dfdf['M'] = dfdf['M'].astype(int)
dfdf['total'] = dfdf['total'].astype(int)
dfdf['Pct'] = dfdf['M'] / dfdf['total'] * 100
dfdf.sort_values(by='Pct', ascending=False)

        M       column   total        Pct
3   79710       depart  118696  67.154748
8   42900     snowfall  118696  36.142751
11   4957     sealevel  118696   4.176215
2    4520         tavg  118696   3.808047
6    4520         heat  118696   3.808047
7    4520         cool  118696   3.808047
5    4492      wetbulb  118696   3.784458
0    3018         tmax  118696   2.542630
1    3016         tmin  118696   2.540945
10   2987  stnpressure  118696   2.516513
14   2759     avgspeed  118696   2.324425
9    2706  preciptotal  118696   2.279774
4    2571     dewpoint  118696   2.166038
12   2190  resultspeed  118696   1.845050
13   2190    resultdir  118696   1.845050

In [14]:
# M -> numeric

for col in df.columns:
    if df[col].name == 'weekday': continue
    elif df[col].dtypes == 'object':
        df[col] = pd.to_numeric(df[col], errors='coerce')
    else: continue

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118696 entries, 0 to 118695
Data columns (total 54 columns):
date           118696 non-null datetime64[ns]
store_nbr      118696 non-null int64
item_nbr       118696 non-null int64
units          118696 non-null int64
station_nbr    118696 non-null int64
tmax           115678 non-null float64
tmin           115680 non-null float64
tavg           114176 non-null float64
depart         38986 non-null float64
dewpoint       116125 non-null float64
wetbulb        114204 non-null float64
heat           114176 non-null float64
cool           114176 non-null float64
sunrise        49541 non-null float64
sunset         49541 non-null float64
snowfall       74553 non-null float64
preciptotal    101316 non-null float64
stnpressure    115709 non-null float64
sealevel       113739 non-null float64
resultspeed    116506 non-null float64
resultdir      116506 non-null float64
avgspeed       115937 non-null float64
BCFG           118696 non-null float64
BLDU           118696 non-null float64
BLSN           118696 non-null float64
BR             118696 non-null float64
DU             118696 non-null float64
DZ             118696 non-null float64
FG             118696 non-null float64
FG+            118696 non-null float64
FU             118696 non-null float64
FZDZ           118696 non-null float64
FZFG           118696 non-null float64
FZRA           118696 non-null float64
GR             118696 non-null float64
GS             118696 non-null float64
HZ             118696 non-null float64
MIFG           118696 non-null float64
PL             118696 non-null float64
PRFG           118696 non-null float64
RA             118696 non-null float64
SG             118696 non-null float64
SN             118696 non-null float64
SQ             118696 non-null float64
TS             118696 non-null float64
TSRA           118696 non-null float64
TSSN           118696 non-null float64
UP             118696 non-null float64
VCFG           118696 non-null float64
VCTS           118696 non-null float64
year           118696 non-null int64
month          118696 non-null int64
day            118696 non-null int64
weekday        118696 non-null object
dtypes: datetime64[ns](1), float64(45), int64(7), object(1)
memory usage: 49.8+ MB

In [93]:
df

,date,store_nbr,item_nbr,units,station_nbr,tmax,tmin,tavg,depart,dewpoint,...,TS,TSRA,TSSN,UP,VCFG,VCTS,year,month,day,weekday
0,2012-11-15,37,5,5568,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
1,2012-11-15,25,45,70,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
2,2012-11-15,25,9,70,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
3,2012-11-15,15,45,62,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
4,2012-11-15,32,9,52,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
5,2012-11-15,40,45,51,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
6,2012-11-15,37,45,44,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
7,2012-11-15,32,45,36,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
8,2012-11-15,15,5,29,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
9,2012-11-15,40,5,29,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
10,2012-11-15,25,81,8,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
11,2012-11-15,15,93,5,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
12,2012-11-15,15,15,4,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
13,2012-11-15,40,15,2,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
14,2012-11-15,25,12,1,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
15,2012-11-15,15,17,1,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
16,2012-11-15,32,19,1,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
17,2012-11-15,37,15,1,13,44,24,34,M,26,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,15,Thu
18,2013-11-21,37,5,3369,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
19,2013-11-21,25,45,61,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
20,2013-11-21,32,9,48,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
21,2013-11-21,40,45,41,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
22,2013-11-21,15,45,39,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
23,2013-11-21,32,45,33,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
24,2013-11-21,25,9,27,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
25,2013-11-21,40,5,24,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
26,2013-11-21,37,45,22,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
27,2013-11-21,15,5,19,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
28,2013-11-21,37,15,10,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
29,2013-11-21,15,15,7,13,28,11,20,M,11,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,11,21,Thu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118666,2012-11-22,39,36,2,8,79,50,M,M,56,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,22,Thu
118667,2012-11-22,39,9,1,8,79,50,M,M,56,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,11,22,Thu
118668,2014-07-19,39,36,2,8,89,73,81,M,72,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,7,19,Sat
118669,2014-07-19,39,9,2,8,89,73,81,M,72,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,7,19,Sat
118670,2014-08-06,39,9,2,8,99,73,86,M,73,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,8,6,Wed
118671,2014-08-16,39,111,2,8,102,79,91,M,74,...,1.0,0.0,0.0,0.0,0.0,0.0,2014,8,16,Sat
118672,2014-08-16,39,36,1,8,102,79,91,M,74,...,1.0,0.0,0.0,0.0,0.0,0.0,2014,8,16,Sat
118673,2014-03-28,39,36,2,8,85,60,73,M,66,...,1.0,0.0,0.0,0.0,0.0,1.0,2014,3,28,Fri
118674,2014-06-03,39,36,2,8,90,75,83,M,75,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,6,3,Tue
118675,2014-06-03,39,9,2,8,90,75,83,M,75,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,6,3,Tue
118676,2014-06-03,39,103,1,8,90,75,83,M,75,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,6,3,Tue
118677,2012-03-20,1,28,2,1,82,41,62,M,45,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,3,20,Tue
118678,2012-03-20,1,9,1,1,82,41,62,M,45,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,3,20,Tue
118679,2012-01-07,1,9,2,1,57,28,43,M,28,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,1,7,Sat
118680,2012-01-07,1,28,1,1,57,28,43,M,28,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,1,7,Sat
118681,2014-02-18,1,28,2,1,30,6,18,M,12,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,2,18,Tue
118682,2014-02-18,1,47,2,1,30,6,18,M,12,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,2,18,Tue
118683,2014-02-18,1,9,1,1,30,6,18,M,12,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,2,18,Tue
118684,2014-02-18,1,40,1,1,30,6,18,M,12,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,2,18,Tue
118685,2014-02-18,1,99,1,1,30,6,18,M,12,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,2,18,Tue
118686,2012-10-30,1,89,1,1,61,52,57,M,M,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,10,30,Tue
118687,2012-10-30,1,28,1,1,61,52,57,M,M,...,0.0,0.0,0.0,0.0,0.0,0.0,2012,10,30,Tue
118688,2014-10-02,45,9,1,16,56,42,49,M,50,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,10,2,Thu
118689,2014-10-02,45,22,1,16,56,42,49,M,50,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,10,2,Thu
118690,2014-10-02,14,9,1,16,56,42,49,M,50,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,10,2,Thu
118691,2014-10-02,14,25,1,16,56,42,49,M,50,...,0.0,0.0,0.0,0.0,0.0,0.0,2014,10,2,Thu
118692,2013-12-25,11,9,1,10,62,43,53,M,44,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,12,25,Wed
118693,2013-12-25,15,45,1,13,44,14,29,M,6,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,12,25,Wed
118694,2013-05-03,39,36,1,8,71,47,59,M,35,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,5,3,Fri
118695,2013-05-03,39,9,1,8,71,47,59,M,35,...,0.0,0.0,0.0,0.0,0.0,0.0,2013,5,3,Fri